### ISSUE TITLE
how to use？

### ISSUE THREAD

**Issue by yeyonghao1** [haq/tweeto#43]

**Comment by haq** [comment]
It is like setting up any Laravel project.

You can follow _https://devmarketer.io/learn/setup-laravel-project-cloned-github-com/_ or follow the steps below.

- Clone the repository.
- Run ```composer install```.
- Copy the .env file and remove .example from the name.
- Open up the .env file.
- Update your APP info.
- Update your database info.
- Run command ```php artisan key:generate```.
- Run command ```php artisan migrate```.
- Make sure you point your users to the /public folder.
